apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy01
  labels:
    app: autodeploy01
  namespace: namespace-workflow01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy01
  template:
    metadata:
      labels:
        app: autodeploy01
    spec:
      containers:
        - name: autodeploy01
          image: acrworkflow1714149505077.azurecr.io/image-workflow-1714149505077:latest
          ports:
            - containerPort: 5000